name: Deploy
on:
  push:
    branches: mian
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      #- uses: actions/checkout@v2
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.SSH_USER}}
        run: |
          ls -la
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/aboutme &&
              sudo cp -rv * /var/www/html/ &&
              sudo systemctl restart apache2
              #git checkout dev &&
              #git fetch --all &&
              #git reset --hard origin/dev &&
              #git pull origin dev &&
              #sudo npm i &&
              #sudo npm run build &&
              #sudo pm2 stop ./dist/index.js &&
              #sudo pm2 start ./dist/index.js
              '
